baseURL   = "http://www.katsecurity.blog/"
languageCode = "en-us"
title     = "Hackthekat home"
theme     = "hello-4s3ti"

[build]
  buildFuture = true

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Hack The Box"
    url = "/hackthebox/"
    weight = 3
    identifier = "htb"   # Unique identifier for this parent

  [[menu.main]]
    name = "Machines"
    url = "/writeups/"
    weight = 5
    parent = "htb"       # This makes it a submenu under Hack The Box
